CREATE TABLE tarefas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    descricao CLOB NOT NULL,
    prioridade VARCHAR2(10) CHECK (prioridade IN ('baixa', 'media', 'alta')) NOT NULL,
    status VARCHAR2(20) CHECK (status IN ('pendente', 'em progresso', 'concluido')) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_criacao DATE DEFAULT SYSDATE NOT NULL,
    email VARCHAR2(255) NOT NULL
);
